services:
  - type: web
    name: kimai
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: kimai-db
          property: connectionString
databases:
  - name: kimai-db
    plan: free
    region: frankfurt
    postgresMajorVersion: 13
